### ISSUE TITLE
problem with frequency

### ISSUE THREAD

**Issue by canh-thu** [marcelo-mason/cccbdb-geometry-parser#1]
Hi, I can run the examples successful with geom and dipole. What I need to get are frequencies. I've tried: python cccbdb.py vibs CH4 shallow. It works and shows {'level': 'B3LYP', 'basis': 'CEP-31G', 'bond': 'freq'}. The data I need are those inside the links and I need to use deep. However when I use "python cccbdb.py vibs CH4 deep", the results are: 
**** Posting formula
**** Fetching data
**** Extracting data
**** Fetching deep data
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
**** Failed, retrying...
Please help me with this problem. Thanks !

**Comment by marcelo-mason** [comment]
Should work now
